### PR TITLE
Code simplification and speedups

### PR DESCRIPTION
**Pull request by jedisct1**
tbak is a great project, thanks for working on this!

However some code is unnecessary or doing unneeded operations.  Here are some simple changes to fix this.

### CODE REVIEW

**Comment by tux3** [comment]
Thanks for the PR !

Unfortunately, there are a couple of issues.
- 6610f8f doesn not compile, this is minor, but it made bisecting a bit harder
- 0e3fcb4 and later breaks it for me, I get a SIGABRT in sodium_bin2hex, called from Crypto::sha512str

Below is a pic of the crash I'm getting :

snapshot1

**Comment by jedisct1** [comment]
Sorry, https://github.com/jedisct1/tbak/commit/5244c8bdcd73de5084a5a8370bc1b1020414bdb4 fixes the buffer size for the hex conversion.

**Comment by jedisct1** [comment]
6610f8f should definitely compile. In fact it shouldn't even compile before since the tbak implementation doesn't match the prototype (the pointer is supposed to be an `unsigned char *`).

**Comment by tux3** [comment]
You made this PR from "master", but sent the new fix to "p1".
Should I close this pr and merge your branch "p1" directly ?

**Comment by tux3** [comment]
I'm still having issues even with the new fix applied.

This is what happens when doing "folder sync" :

```
Syncing with somewhere...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Crypto decrypt: Invalid or forged cyphertext
<SIGABRT>
```

It seems that crypto_box_open_easy fails to decrypt the "folder stats" reply from the server.
snapshot2

**Comment by jedisct1** [comment]
Can you try with  with b78c508d824920277cf2ab68608c7cd24ecc558b in addition to it? (branch p1).

**Comment by tux3** [comment]
It seems to work with b78c508.

**Pull request merged**
